### ISSUE TITLE
Receiving TypeError: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by 0xdewy** [NodeFactoryIo/atom-solidity-comments#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 3.1.4
**OS**: "Manjaro Linux"
**Thrown From**: [solidity-comments](https://github.com/nodefactoryio/atom-solidity-comments) package 2.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'line' of undefined

```
At /home/.atom/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1052

TypeError: Cannot read property 'line' of undefined
    at ASTBuilder._loc (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1052:23)
    at ASTBuilder.meta (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1070:29)
    at ASTBuilder.createNode (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1079:34)
    at ASTBuilder.visit (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1108:15)
    at ASTBuilder.SimpleStatement (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:447:17)
    at ASTBuilder.visit (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1101:38)
    at ASTBuilder.Statement (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:444:17)
    at ASTBuilder.visit (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1101:38)
    at /packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1089:19)
    at Array.map (<anonymous>)
    at ASTBuilder.visit (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1088:16)
    at ASTBuilder.Block (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:404:24)
    at ASTBuilder.visit (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1101:38)
    at ASTBuilder.ConstructorDefinition (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:101:22)
    at ASTBuilder.visit (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1101:38)
    at ASTBuilder.ContractPart (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:95:17)
    at ASTBuilder.visit (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1101:38)
    at /packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1089:19)
    at Array.map (<anonymous>)
    at ASTBuilder.visit (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1088:16)
    at ASTBuilder.ContractDefinition (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:84:22)
    at ASTBuilder.visit (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1101:38)
    at /packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1089:19)
    at Array.map (<anonymous>)
    at ASTBuilder.visit (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1088:16)
    at ASTBuilder.SourceUnit (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:46:22)
    at ASTBuilder.visit (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/ASTBuilder.js:1101:38)
    at Object.parse (/packages/solidity-comments/node_modules/solidity-parser-antlr/dist/index.js:78:21)
    at generate (/packages/solidity-comments/node_modules/@nodefactory/solidity-comments-core/dist/index.js:40:43)
    at generateCommentsFromText (/packages/solidity-comments/node_modules/@nodefactory/solidity-comments-core/dist/index.js:28:10)
    at Object.run (/packages/solidity-comments/lib/atom-solidity-comments.js:29:25)
    at HTMLElement.atomSolidityCommentsToggle (/packages/solidity-comments/lib/atom-solidity-comments.js:19:51)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:384:43)
    at CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:273:17)
    at AtomEnvironment.dispatchContextMenuCommand (/usr/lib/atom/src/atom-environment.js:1345:19)
    at EventEmitter.outerCallback (/usr/lib/atom/src/application-delegate.js:305:47)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -8:17.2.0 core:paste (input.hidden-input)
     -8:14.4.0 autocomplete-plus:confirm (input.hidden-input)
  2x -8:13.7.0 core:save (input.hidden-input)
     -7:50.7.0 editor:newline (input.hidden-input)
  5x -7:48.8.0 core:backspace (input.hidden-input)
     -7:32.1.0 snippets:next-tab-stop (input.hidden-input)
     -7:32.1.0 snippets:expand (input.hidden-input)
     -7:32.1.0 editor:indent (input.hidden-input)
     -7:30.2.0 autocomplete-plus:confirm (input.hidden-input)
 15x -7:27.6.0 core:backspace (input.hidden-input)
     -7:22.3.0 editor:newline (input.hidden-input)
  3x -7:20.9.0 autocomplete-plus:confirm (input.hidden-input)
     -7:12.8.0 core:save (input.hidden-input)
     -7:03.2.0 core:backspace (input.hidden-input)
     -0:49 core:save (input.hidden-input)
     -0:42.7.0 atom-solidity-comments:toggle (div.line.cursor-line)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.18.5 
file-icons 2.1.30 
highlight-selected 0.14.0 
language-solidity 0.1.1 
language-vyper 0.2.0 
linter-solidity 0.5.0 
pigments 0.40.2 
react 0.18.0 
solidity-comments 2.1.1 
wakatime 7.0.7 
```

**Comment by zemse** [comment]
I am also getting same error with latest version of Atom 1.39.1
